### ISSUE TITLE
string=state cache not found

### ISSUE THREAD

**Issue by Flolon** [RambIing/ringbot#1]
I'm getting "string=state cache not found."

**Comment by RambIing** [comment]
Looks like an issue returned within DiscordGo, do you have a specific line? Otherwise, what causes it to error? It might be helpful to show what permissions you gave the bot (I'll add suggested permissions in a bit)

**Comment by Flolon** [comment]
error getting guild info: &{%!e(string=state cache not found)}
[# # # #](https://github.com/RambIing/ringbot/blob/bcdb596669d95b96a9ef58eaac2965455fec4e53/commands/call.go#L59)

**Comment by Flolon** [comment]
These are the perms it haas
![image](https://github.com/user-attachments/assets/be56a321-6d67-4d64-98cb-c3b80646dfc7)

i've been thinking discordgo but idk much about go or discordgo

**Comment by RambIing** [comment]
Can't repro. Please add to this if anyone else gets this error.
